CREATE DATABASE khang

CREATE table SANPHAMBANH (
MASP INT PRIMARY KEY,
TENSP NVARCHAR,
MOTA NVARCHAR,
GIA FLOAT,
SOLUONG INT,
HINHANH NVARCHAR
)
CREATE TABLE DANHMUCSP (
MADM INT PRIMARY KEY,
TENDM NVARCHAR
)
CREATE TABLE SANPHAM_DANHMUC (
MASP_DM INT PRIMARY KEY,
MASP INT,
MADM INT
)
ALTER TABLE SANPHAM_DANHMUC ADD FOREIGN KEY(MASP) REFERENCES SANPHAMBANH(MASP)
ALTER TABLE SANPHAM_DANHMUC ADD FOREIGN KEY(MADM) REFERENCES DANHMUCSP(MADM)


CREATE TABLE DONHANG (
MADH INT PRIMARY KEY,
NGAYDAT DATE,
MAKH INT
)
ALTER TABLE DONHANG ADD FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)



CREATE TABLE CTDH (
MACTDH INT PRIMARY KEY,
MADH INT,
MASP INT,
SOLUONG INT,
GIATIEN INT
)
ALTER TABLE CTDH ADD FOREIGN KEY(MASP) REFERENCES SANPHAMBANH(MASP)
ALTER TABLE CTDH ADD FOREIGN KEY(MADH) REFERENCES DONHANG(MADH)




CREATE TABLE KHACHHANG(
MAKH INT PRIMARY KEY,
TENKH NVARCHAR,
EMAIL NVARCHAR,
DIENTHOAI NUMERIC,
DIACHI NVARCHAR
)
CREATE TABLE TAIKHOAN(
MATK INT PRIMARY KEY,
TENDANGNHAP NVARCHAR,
MATKHAU NVARCHAR,
EMAIL NVARCHAR,
LOAITAIKHOAN NVARCHAR
)
CREATE TABLE LICHSUDANGNHAP(
MALS INT PRIMARY KEY,
MATK INT,
THOI_GIAN_DANG_NHAP TIME
)
ALTER TABLE LICHSUDANGNHAP ADD FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK)



CREATE TABLE DIADIEMGIAOHANG(
DIA_DIEM_ID INT PRIMARY KEY,
DIA_CHI_GH NVARCHAR,
GHICHU NVARCHAR
)









DROP TABLE SANPHAMBANH;
DROP TABLE DANHMUCSP;
DROP TABLE SANPHAM_DANHMUC;
DROP TABLE DONHANG;
DROP TABLE CTDH;
DROP TABLE KHACHHANG;
DROP TABLE TAIKHOAN;
DROP TABLE LICHSUDANGNHAP;
DROP TABLE DIADIEMGIAOHANG;

